JamfProtectAlertsDemo_CL
| where TimeGenerated >= ago(7d)
| where EventResult == "Prevented"
| project
    TimeGenerated,
    DvcHostname,
    TargetProcessName,
    TargetProcessSHA256,
    TargetbinarySignerType,
    TargetBinarySigningTeamID,
    TargetProcessCommandLine,
    TargetProcessCurrentDirectory,
    ParentProcessName,
    TargetFilePath,
    EventMessage,
    EventSeverity,
    EventOriginalType
| order by TimeGenerated desc
| take 100
