JamfProtectAlertsDemo_CL
| where TimeGenerated >= ago(7d)
| where EventType in ("USB", "UsbBlock")
| summarize
    EventCount    = count(),
    BlockedCount  = countif(EventResult == "Prevented"),
    AllowedCount  = countif(EventResult == "Allowed"),
    EventActions  = make_set(EventResult, 5),
    DeviceSerials = make_set(DvcSerial, 10),
    FirstSeen     = min(TimeGenerated),
    LastSeen      = max(TimeGenerated)
    by DvcHostname, EventType, EventSeverity
| order by EventCount desc
